export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';
export const SET_LOGIN_FINISHED = 'SET_LOGIN_FINISHED';
export const SET_USERINFO = 'SET_USERINFO';
export const SET_LOGININFO = 'SET_LOGININFO';
export const WEB_LOGIN = 'WEB_LOGIN';
export const CHECK_LOGIN = 'CHECK_LOGIN';
export const USER_CHECK_LOGIN = 'USER_CHECK_LOGIN';
export const WEB_CODE_LOGIN = 'WEB_CODE_LOGIN';
export const LOGIN_OUT = 'LOGIN_OUT';
export const LOGOUT = 'LOGOUT';
export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_BIND_USER_INFO = 'GET_BIND_USER_INFO';
export const SET_BIND_USER_INFO = 'SET_BIND_USER_INFO';
export const GET_FRIENDS_LIST = 'GET_FRIENDS_LIST';
export const SET_FRIENDS_LIST = 'SET_FRIENDS_LIST';
export const GET_GROUP_LIST = 'GET_GROUP_LIST';
export const SET_GROUP_LIST = 'SET_GROUP_LIST';
export const SET_DISCUSSION_LIST = 'SET_DISCUSSION_LIST';
export const GO_CHAT_HOME = 'GO_CHAT_HOME'; //解散群聊后返回聊天首页
//
// export const SET_HISTORY_CHAT = 'SET_HISTORY_CHAT';
export const CHAT_REST_SEND = 'CHAT_REST_SEND';
export const SET_CHAT = 'SET_CHAT';
export const UPDATE_CHAT_RECORD = 'UPDATE_CHAT_RECORD'; //
export const SET_GROUPCHAT = 'SET_GROUPCHAT';
export const CLEAR_CHAT = 'CLEAR_CHAT';
export const CLEAR_CHAT_ALL = 'CLEAR_CHAT_ALL'; //重置聊天相关所有store
export const SET_APPLY_FRINED_NUMBER = 'SET_APPLY_FRINED_NUMBER';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const GET_LAST_MSG_LIST = 'GET_LAST_MSG_LIST';
export const ADD_LAST_MSG_LIST = 'ADD_LAST_MSG_LIST';
export const DEL_LAST_MSG_LIST = 'DEL_LAST_MSG_LIST';
export const SET_LAST_MSG_LIST = 'SET_LAST_MSG_LIST';
export const GET_MSG_INFO = 'GET_MSG_INFO';
export const SET_UN_READ_MSG = 'SET_UN_READ_MSG';
export const SET_CLEAN_UN_MSG = 'SET_CLEAN_UN_MSG';

export const SET_DISTURB = 'SET_DISTURB';

export const GET_NEW_MEG = 'GET_NEW_MEG';

export const GET_SEARCH_GROUP = 'GET_SEARCH_GROUP';
export const SET_SEARCH_GROUP = 'SET_SEARCH_GROUP';

export const GET_SEARCH_FRIENDS = 'GET_SEARCH_FRIENDS';
export const SET_SEARCH_FRIENDS = 'SET_SEARCH_FRIENDS';

export const FIND_USER_RSA_INFO = 'FIND_USER_RSA_INFO';
export const FIND_LATEST_USER_RSA = 'FIND_LATEST_USER_RSA';
export const SET_USER_RSA_INFO = 'SET_USER_RSA_INFO';
export const SET_USER_PRIVATE_KEY = 'SET_USER_PRIVATE_KEY';
export const GET_PUB_KEY_AND_SAVE = 'GET_PUB_KEY_AND_SAVE';

export const UPDATE_CACHE = 'UPDATE_CACHE';
export const SET_TRANSFER_ITEM = 'SET_TRANSFER_ITEM';
export const SET_DOWNLOAD_FILE_INFO = 'SET_DOWNLOAD_FILE_INFO';

export const SET_CHAT_LIST = 'SET_CHAT_LIST';
export const SET_REJECT_FRIEND_NUMBER = 'SET_REJECT_FRIEND_NUMBER';
export const SET_REQUEST_FRIEND_NUMBER = 'SET_REQUEST_FRIEND_NUMBER';
export const SET_TOTAL_SYSTEM_NUMBER = 'SET_TOTAL_SYSTEM_NUMBER';
export const UPDATE_CHAT_SEND_STATUS = 'UPDATE_CHAT_SEND_STATUS';
export const UPDATE_MESSAGE_READ = 'UPDATE_MESSAGE_READ';
export const SEND_READ_MESSAGE = 'SEND_READ_MESSAGE';
export const SOCKET_STATUS = 'SOCKET_STATUS';
export const NET_STATUS = 'NET_STATUS';
export const SET_DRAF_LIST = 'SET_DRAF_LIST';
export const SET_DRAFT_LIST_FROM_SQLITE = 'SET_DRAFT_LIST_FROM_SQLITE';
export const DEL_DRAF_LIST = 'DEL_DRAF_LIST';
export const UPDATE_DRAF_LIST = 'UPDATE_DRAF_LIST';
export const GO_MESSAGE_PAGE = 'GO_MESSAGE_PAGE';
export const SET_SCREEN_SELECT = 'SET_SCREEN_SELECT';
export const SET_NO_NOTICE_SESSION = 'SET_NO_NOTICE_SESSION';
export const GET_USER_SIG = 'GET_USER_SIG';
export const SET_USER_SIG = 'SET_USER_SIG';
export const REMOVE_ALL_LISTENERS = 'REMOVE_ALL_LISTENERS';
export const SET_AUDIO_WINDOW_DISPLAY = 'SET_AUDIO_WINDOW_DISPLAY';
export const SET_CURRENT_AUDIO = 'SET_CURRENT_AUDIO';
export const CLEAR_CURRENT_AUDIO = 'CLEAR_CURRENT_AUDIO';
export const UPDATE_ISAT_SESSION = 'UPDATE_ISAT_SESSION';
export const SET_NEW_MESSAGE_SOUND_REMIND = 'SET_NEW_MESSAGE_SOUND_REMIND';
export const  NOTIFY_UPDATE_VERSION = 'NOTIFY_UPDATE_VERSION';


export const VIEW_PERSONAL_APPEAL = 'VIEW_PERSONAL_APPEAL';
export const CLEAR_PERSONAL_APPEAL = 'CLEAR_PERSONAL_APPEAL';
export const UPDATE_PERSONAL_APPEAL = 'UPDATE_PERSONAL_APPEAL';

export const LOGIN_FINISHED = 'LOGIN_FINISHED';
export const SYNC_DATA_PROGRESS = 'SYNC_DATA_PROGRESS';
export const WILL_SYNC_DATA = 'WILL_SYNC_DATA';
export const CHAT_VIDEO_DOWNLOAD_PERCENT = 'CHAT_VIDEO_DOWNLOAD_PERCENT';
export const CLEAR_FILE_DOWNLOAD = 'CLEAR_FILE_DOWNLOAD';
export const SET_VIDEO_EXIST = 'SET_VIDEO_EXIST';

export const IS_IN_SYNCDATA_PAGE = 'IS_IN_SYNCDATA_PAGE';
export const IS_SHOW_CLOSE_SYNCDATA = 'IS_SHOW_CLOSE_SYNCDATA';

export const TO_BE_HANDLED_MSGS = 'TO_BE_HANDLED_MSGS';

export const WIN_ACTIVE = 'WIN_ACTIVE';
export const UPDATE_CHAT_CONTENT = 'UPDATE_CHAT_CONTENT';
export const UPDATE_MESSAGE_DISABLE = 'UPDATE_MESSAGE_DISABLE';